---CORREÇÃO SOMATIVA 01 - OFICINA REBECCA

CREATE DATABASE IF NOT EXISTS OFICINA_REBECCA;

USE OFICINA_REBECCA;

CREATE TABLE IF NOT EXISTS CLIENTES(
    ID_CLIENTES INT AUTO_INCREMENT PRIMARY KEY,
    NOME varchar(60) not null,
    CPF varchar(14) not null unique,
    EMAIL varchar(50),
    TELEFONE varchar(14),
    endereço varchar(20),
    status_cliente ENUM('ATIVO', 'DESATIVADO') DEFAULT `ATIVO`

);

CREATE TABLE IF NOT EXISTS VEICULOS (
    ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
    PLACA CHAR(8) NOT NULL UNIQUE,
    TIPO enum ("CARRO", "CAMINHONETE", "MOTO") default 'CARRO',
    COR VARCHAR(20),
    QUILOMETRAGEM FLOAT,
    TIPO_MOTOR ENUM ('ELÉTRICO', 'COMBUSTÃO'),
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);

create table IF NOT EXISTS MARCA (
id_marca int auto_increment primary key,
ano_LANÇAMENTO year,
NOME varchar(30) not null,
PAIS varchar(50),
SITE_MARCA VARCHAR(100),
STATUS_MARCA ENUM,
DATA_CADASTRO TIMESTAMP DEFAULT
CURRENT_TIMESTAMP
);


---vizualizar todos os BD

SHOW SCHEMAS;

---VIZUALIZAE TABELAS DO BD
SHOW TABLES; 

--- DESCRIÇÃO SOBRE INFORMAÇÕES DAS TABELAS 

DESCRIBE CLIENTES;

create table IF NOT EXISTS MODELOS (
    id_modelos int auto_increment primary key,
    COR VARCHAR (20),
    ANO_MODELO YEAR,
    TIPO enum ("MANUAL","ELETRICO") default 'MANUAL',
    VALOR_MODELO DECIMAL(10,2),
    CATEGORIA ENUM ('SUV', 'HATCH', 'SEDAN', 'MOTO ESPORTIVA'),
    NOME_MODELO VARCHAR(50),
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);

create table IF NOT EXISTS FUNCIONARIOS (
    id_funcionarios int auto_increment primary key,
    NOME_FUNCIONARIOS varchar(60) not null,
    SALARIO DECIMAL(10,2) NOT NULL,
    CARGO VARCHAR(60) NOT NULL,
    TELEFONE varchar(14),
    CPF_FUNCIONARIO varchar(14) not null unique,
    STATUS_FUNCIONARIO ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO'
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);


create table IF NOT EXISTS SERVIÇOS (
    id_servicos int auto_increment primary key,
    DESCRICAO_PROBLEMA VARCHAR(60) not null,
    TIPO_SERVICO varchar(50) not null,
    DATA_INICIO datetime not null,
    PRECO_SERVICO decimal(10,2) DEFAULT 0.00 NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    STATUS_SERVICO ENUM('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE'
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);

create table IF NOT EXISTS PEÇAS (
    id_pecas int auto_increment primary key,
    NOME_PECA varchar(60) not null,
    LOCAL varchar(50),
    VALOR_PECA decimal(10,2) NOT NULL,
    TAMANHO varchar(14) not null,
    VALIDADE DATE NOT NULL,
    STATUS_PECA ENUM('DISPONIVEL', 'INDISPONIVEL'),
    QTDE_CADASTRO INT,
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);


create table IF NOT EXISTS ORDEM_DE_SERVICO (
    id_ordemserviço int auto_increment primary key,
    PRIORIDADE ENUM('URGENTE', 'SIMPLES') NOT NULL DEFAULT 'SIMPLES',
    PRAZO_FINAL DATE NOT NULL,
    RANKING_ORDEM VARCHAR(40) NOT NULL,
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_CASO VARCHAR(250) NOT NULL,
    STATUS_SERVICO ENUM('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE'
);

create table IF NOT EXISTS PAGAMENTO (
    id_pagamento int auto_increment primary key,
    FORMA enum ("PIX", "BOLETO", "DEBITO", "CREDITO", "DINHEIRO") default 'BOLETO' NOT NULL,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 000.00,
    CPF varchar(14) not null unique,
    DATA_VENCIMENTO date NOT NULL,
    STATUS_PAGAMENTO VARCHAR(30),
    COMPROVANTE INT,
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);

create table IF NOT EXISTS FORNECEDORES (
    id_fornecedores int auto_increment primary key,
    razao_social varchar(60) not null,
    TELEFONE_CONTATO varchar(14),
    CNPJ varchar(20) not null,
    VALOR_DESCONTO decimal,
    DATA_DE_FORNECIMENTO datetime,
    EMAIL VARCHAR(100) NOT NULL,
    INSCRICAO_ESTADUAL CHAR(10),
    SEGMENTO_FORNECEDOR VARCHAR(50) NOT NULL,
    ENDERECO_FORNECEDOR VARCHAR(100) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT
    CURRENT_TIMESTAMP
);

-- ALTERAÇÕES INSERINDO CAMPOS NOVOS NAS TABELAS

ALTER TABLE CLIENTES ADD IDADE INT;

ALTER TABLE FUNCIONARIOS ADD ENDERECO VARCHAR(100);

ALTER TABLE MARCA ADD OBSERVACAO VARCHAR(250);

ALTER TABLE MODELOS ADD TIPO_MODELO VARCHAR (50);

ALTER TABLE ORDEM_DE_SERVICO ADD AREA_SERVICO VARCHAR(60) NOT NULL;

ALTER TABLE PEÇAS ADD PESO FLOAT NOT NULL;

ALTER TABLE SERVIÇOS ADD OBSERVACAO VARCHAR(60);

ALTER TABLE VEICULOS ADD MODELO VARCHAR (60);

ALTER TABLE fornecedores ADD TIPO_ENVIO VARCHAR(50);

ALTER TABLE pagamento ADD DESCONTO DECIMAL(10,2) DEFAULT 0.00 NOT NULL;

-- EXCLUSÃO DE CAMPOS NAS TABELAS

ALTER TABLE CLIENTES DROP COLUMN IDADE;

-- RENOMEAR TABELA
RENAME TABLE MODELOS TO MODELOS_FAB;